language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sonnyjon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sonnyjon/docker-react npm run test
